language: node_js
node_js:
- 8.9.2
notifications:
  email:
    on_success: change
    on_failure: always
script:
- npm test
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: kxACRj7IMARrY7ll4wGi5VDoQeLtxKE7hwsUi/ARhPSKSgKapfshKPom/Mf+ykyGJ++4BM+NPFO/LKCbfomEvLoPRtznkWS9pX7QpdBmhQhg9y1cqDojkCt8TMqfo0jwNrPpOGFpy1Iq+YuJLB9g3gR0VDZbWhr0fGUbK7EHocg+lPV5hPjEHO/+dnv8AmoHsulYMW9nqy/ZEKzhBon/aoz65NluAFoOuTlpLjpx3xX6k7hEUedXgWoiA0Z4ijigvgbPK/txsZ/ujQK7Qh3Sl1RiSjhXn53XnGFQPLx6Xy34Pu5UcIgnl8jGhA1hBoK20OrSyZO+mhu/mZ30jl1jXRcMlBHdF8xAfifDEZ5hwsX54tcUQVE/MsI7KSWvgLaMFy4HWOmW7JicMBF+26N5EcAFa4qVliJ7IeVVbaOL2C517sx3ut5dyQwbZ7Ve2vxuEFqLx2JaiNPcoOodp5vSisvkjamxvhU8XliwAQuj9MqPyDi6HwGVGOdnSeTg1nrJ0FNTYOrp6UmGI+X7o1tuotVN+RmvC03QL8clrmh0BSbTAmDSEPgmmhFQksaJiPaEXkLjsEkCB0MANo3WEVrdh4tYEFoLQ4Kf9eM89fDkT6Ee62SzNUNGXduLiPQ12qZrRRsh2LIkb+mfrgqDEf+kVuoXLFPMlpN5FtWgs/5apfc=
  on:
    tags: true
    repo: coveo/exponential-backoff
    branch: master
