language: node_js
node_js:
- 8.9.2
notifications:
  email:
    on_success: change
    on_failure: always
script:
- npm test
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: v2fMGSalGYb5OKVRoe6bDW1Fk4UA6w6WiG3QlMlAXXf5GlUg+LDf+56joOBGF0J7IPm0atmlFlOM3E4XAOUkkjQMawJ+tcuD4ccHOCV78YimhUHRtYZ1Q7Jz6OjTHvurMENBAFEH2UnuWwGpYDT96uNrq4s+tELk5hDQ+IvPm2LBm54MunUhOoxpaJsYS/xKiYfxKAxC3SSK04GljJR2b1ghVheCJpScWPS7iqNDVJ+39sQsDhKA+j4OFnwn/bxTWYzNJrlczquU52f7P6qyHfVExA2WtgC/hnhIGZ2IJeyOMg71BOtRP7JFA/EpwactSijlst5DfJBSIT5wMpJ+FG7UvCpIjq5OkZPwq7NyblCY9D52C99/fK8WxfTzvop1zM1R8U9QWKR86KuBaBMwdYO+1BU5FP3HUw6MMpVQwpxC7G0wotmEH0A7dA2gYNC3bf4zzOyw0WZHxUpOpDVRPMzJGG+r/jEe0H+ek5SX6H0szggCHKgd4wYTbkfbDnUXtjTdKNepJCJinQZ6G6hDWWZysUXNGdFH4zUOk4P1oUN93e3fUnanMi5NUm81YtpuhV4h/WFLze194F7ZI3uH5sGkTxGFTg0ayQGPAgIK4zIkXsyBFCvSbrB6E32FZ2W/EiQHA78VTefy8Szxp6UlnJdKjiz1veIV34OkEdjc8Kc=
  on:
    tags: true
    repo: coveo/exponential-backoff
    branch: master
