language: node_js
node_js:
- 8.9.2
script:
- npm test
before_deploy:
- npm run build
deploy:
  provider: npm
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: vKSeZLR0qyeOiV1YC1v2eMGa8nFNIe5fng2k6GyB8A++rPtV5+vHpY3XrliXZ4/KiufNnKkrYCaVAwYTs7qeWLp24qiPTEfKJtfshBHnZ13RTwRf086/n+N4n6i1nqKmbd9h6bXhb9Eucgo+uFu5hnWSL9y3YXc/FHR3Q22eMd06FnTDn5NykwCMge7SQGZvg08raWPMnOwnpf1ngeMFpfXpzP13dSDA6RoX+VAdQpZV3FNqjSbpgt3K1oq3Q3zylUGgzCJHKbUBlyFbCDUQFmdrP7sFKhsamwz7Y+lIQVqx2/1W9KnCKrExT4e/trH0vQeKrhabBBuo2K6EklvZqM8zVoHUjxsaR+fFlXfAz0TE3y26/npzTWz3Aw+Nke5mgjVnfvDJS0o5MXPbuWcf5ynFQrVzq+CD5GKjxnNCo3bw/y8lQdMK9Z0/LEKbkZgCkcPKZFMSFYbjZEcYMnq35yg8vXsi7WT0KSPYYZZzCBMXCxMXqqq6U7FMI7QlAGp9RoLKY+bTA7NeFKgdNLzuidosvO1yiIybGy77YanLSpEkfHQHDq3v9w6ae1hR3er+ytPbxL9/PqgNtXiEzAwIDt43sRtPtUvNyTju3NQ7D65W+L01pmtW3XUwP1tiyH58Tf1nNlUdSr/401iF8m2Z/EJ2C75xBQ11e7h6UBIJ4ZY=
  on:
    tags: true
    repo: coveo/exponential-backoff
    branch: master
