language: node_js
node_js:
- 8.9.2
notifications:
  email:
    on_success: change
    on_failure: always
script:
- npm test
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: M3p7E9P3giuKbh0kOWP5P6pXhjxMFeZy4dT6NFYZQ0JICJ+UPaxHHUKF59wPTcimjOgKV3YZW3iQOQlcOxFZA7v9EwIPumGHvPx8b/DEBqEl1GzawhD5jBC534YS+Srt7aWR4ngExKzs/fBdLWtjYU3MyuOhdfhlCTPzwsImkoXb2pgt+0nfDf761jflDiRbtU/LrpLtr/8XEejSp6V+mGVmp73lzo66Kqahip+k7fmo5Y5SeO5Du4kIgLkElDEW6VfwSFno/nbHZZ5QfZpf2Rb9HF3LBWsiNo/TzAfswfkrnWDo7M2J4E5Rjgrqx8+Wwc2jTmebptxptg5DfHocpO4TkTDB8hWzbXQZlwvvOFasKQeXkJfwdBYnRDg8kfFB0ltZLbQLNMTh3zxzpUQnxIoAXOJwgutpD3tx3xaf6sNUgHOngdjpqzsAdIQeLAgX39wSU1pLfsZ29F1oYp7WNyOLys2B0/tAKgmxXkNcQuGa2HA7xCVRQO67qoeN6l/7VSBpYoq/0pBdqJyCX8jAXUqOgp2rN+6a1ibu8HwwK9jeWaUYVfaNdbFauyh7MqhJUFbbEx2D/LfUt2EQyBUYjXw8hqpniEduJ9ps7rSNILyBPerZ12YKNR2vqwRZUOXX/jummK6rbXCPnMdQXYgvvJiHVUjANTMOQY9tHve8yQI=
  on:
    tags: true
    repo: coveo/exponential-backoff
    branch: master
