language: node_js
node_js:
- 8.9.2
notifications:
  email:
    on_success: change
    on_failure: always
script:
- npm test
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: LyqRGyg51Bh2NyVYac2iBRl2otpE0Ae/UpJkTR7lU8ADv7XzirJDFKKkEctptX+Q03QiYc0TKO+j4P+T13QZ8SQgsIOcZdESM9tLyzeeB0qGHXJuw0kcu10pJKkwIre/WfxHYBDKpF0+DHeWy2mDHT2/pQg9drHS1Y2KGIw+kMARguenWYE3WUbxSnVkR4sNbtahN36pgbgMYb+Pn9PkZKsYEEYyEHCFvTJqQp8dbXNlQ2xNora5SQDmuUV0QqLbOzLIwaVfpx9YP66dOD/txH0PFmbQTNhVmSymwzF905UoKQsA+10r9RJribshqBcPgYFuAnD/XRUpxl919SsDhWJXzzUvX/lN4TPhq8aUrxJF4QTQmnOG/tcAhxWd8xONBOgI2t+pVBsZ68FOlG+U04ZoC2XrYucprNVsplm4ANXW+Vt7qArFF+IgV1EDnu3ntbUc7OtahS5sW8H0uMBNuJVfvwu8zqjr4i2A9Ve4MPYCJfifV60uwMdaTZ7rbYiL+b0eU42ZzJ9Gj3VGSl895WuCIB2aSxLyDdJDGPvlu4/642sUzriPEg0BWOxSwtGppf8UHRbVnWzpheIUoQP0E+OeW6QNQKyXafA/VJl4x4moLMesDe0uUyN33aR+V0hi+PLE0YTKR/Yj0aeMfLa+HGMzSzQt0FHl5uavuen9aAA=
  on:
    tags: true
    repo: coveo/exponential-backoff
    branch: master
